normal:
    key: 'rtt'
server:
    port: 9090

spring:
    profiles:
        include: dev,prod
        active: dev

management:
    endpoints:
        web:
            base-path: /actuator
            exposure:
#                beans, conditions, env, health, info
                include: '*'